# Generated by Django 3.2 on 2021-05-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210509_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='loungeFollowers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='loungeFollowing',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='numOfLounges',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=128, null=True)),
                ('website', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('numOfLounges', models.IntegerField(default=0, null=True)),
                ('loungeFollowers', models.ManyToManyField(null=True, related_name='_users_profile_loungeFollowers_+', to='users.Profile')),
                ('loungeFollowing', models.ManyToManyField(null=True, related_name='_users_profile_loungeFollowing_+', to='users.Profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
