# Generated by Django 3.2 on 2021-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loungeFollowers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_users_profile_loungeFollowers_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loungeFollowing',
            field=models.ManyToManyField(blank=True, null=True, related_name='_users_profile_loungeFollowing_+', to='users.Profile'),
        ),
    ]
