# Generated by Django 3.2 on 2021-04-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('isYoutube', models.BooleanField(default=False)),
                ('isAmazon', models.BooleanField(default=False)),
                ('isBitcoin', models.BooleanField(default=False)),
                ('isTiktok', models.BooleanField(default=False)),
                ('isSpotify', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('src', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=500)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='create.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit', to='create.lounge')),
            ],
        ),
    ]
