# Generated by Django 3.2 on 2021-05-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField(max_length=10000000, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('isYoutube', models.BooleanField(default=False)),
                ('isAmazon', models.BooleanField(default=False)),
                ('isBitcoin', models.BooleanField(default=False)),
                ('isTiktok', models.BooleanField(default=False)),
                ('isSpotify', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sir', max_length=500)),
                ('lounge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='create.lounge')),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit', to='create.lounge')),
            ],
        ),
    ]
