# Generated by Django 3.2 on 2021-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_lounge_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='followers',
            field=models.IntegerField(max_length=10000000, null=True),
        ),
    ]
