# Generated by Django 3.2 on 2021-05-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_lounge_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='src',
        ),
    ]
