# Generated by Django 3.2 on 2021-05-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_auto_20210510_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='lounge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='create.lounge'),
        ),
    ]
