# Generated by Django 3.2 on 2021-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_alter_videos_lounge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(default='sir', max_length=500),
        ),
    ]
