# Generated by Django 3.2 on 2021-05-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_alter_videos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='lounge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='create.lounge'),
        ),
    ]
