# Generated by Django 3.2 on 2021-05-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0007_alter_videos_lounge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
